#ifndef __EFFECT_H_H
#define __EFFECT_H_H
const char * sys_effect[] = {
"LO sys_restart_syscall",
"PR sys_exit",
"PR sys_fork",
"FD sys_read",
"FD sys_write",
"FD FI sys_open",
"FD sys_close",
"PR sys_waitpid",
"FI FD sys_creat",
"FI sys_link",
"FI sys_unlink",
"PR FI sys_execve",
"FI sys_chdir",
"TI sys_time",
"FI sys_mknod",
"FI sys_chmod",
"FI sys_lchown16",
"ZZ",
"FI sys_stat",
"FD sys_lseek",
"PR sys_getpid",
"FI sys_mount",
"FI sys_oldumount",
"ID sys_setuid16",
"ID sys_getuid16",
"TI sys_stime",
"PR sys_ptrace",
"SI sys_alarm",
"FD sys_fstat",
"SI sys_pause",
"FI TI sys_utime",
"ZZ",
"ZZ",
"FI sys_access",
"PR sys_nice",
"ZZ",
"FI sys_sync",
"SI PR sys_kill",
"FI sys_rename",
"FI sys_mkdir",
"FI sys_rmdir",
"FD sys_dup",
"FD sys_pipe",
"TI sys_times",
"ZZ",
"ME sys_brk",
"ID sys_setgid16",
"ID sys_getgid16",
"SI sys_signal",
"IP sys_geteuid16",
"ID sys_getegid16",
"PR sys_acct",
"FI sys_umount",
"ZZ",
"FD LO sys_ioctl",
"FD LO sys_fcntl",
"ZZ",
"PR ID sys_setpgid",
"ZZ",
"LO sys_olduname",
"FI sys_umask",
"FI sys_chroot",
"FI sys_ustat",
"FD sys_dup2",
"PR sys_getppid",
"PR ID sys_getpgrp",
"PR ID sys_setsid",
"SI sigaction",
"SI sys_sgetmask",
"SI sys_ssetmask",
"ID sys_setreuid16",
"ID sys_setregid16",
"SI sigsuspend",
"SI sys_sigpending",
"LO sys_sethostname",
"ID PR sys_setrlimit",
"ID PR sys_old_getrlimit",
"ID PR sys_getrusage",
"TI sys_gettimeofday",
"TI sys_settimeofday",
"ID sys_getgroups16",
"ID sys_setgroups16",
"LO sys_old_select",
"FI sys_symlink",
"FI sys_lstat",
"FI sys_readlink",
"PR FI sys_uselib",
"FI LO sys_swapon",
"LO sys_reboot",
"FI sys_old_readdir",
"FI ME sys_old_mmap",
"FI ME sys_munmap",
"FI sys_truncate",
"FD sys_ftruncate",
"FD sys_fchmod",
"FD sys_fchown16",
"PR sys_getpriority",
"PR sys_setpriority",
"ZZ",
"FI sys_statfs",
"FD sys_fstatfs",
"LO sys_ioperm",
"NE sys_socketcall",
"LO sys_syslog",
"SI TR sys_setitimer",
"SI TR sys_getitimer",
"FI sys_newstat",
"FI sys_newlstat",
"FD sys_newfstat",
"LO sys_uname",
"LO sys_iopl",
"LO sys_vhangup",
"ZZ",
"LO sys_vm86old",
"PR sys_wait4",
"FI sys_swapoff",
"LO sys_sysinfo",
"IP sys_ipc",
"FD sys_fsync",
"SI sys_sigreturn",
"PR sys_clone",
"NE sys_setdomainname",
"LO sys_newuname",
"LO sys_modify_ldt",
"LO sys_adjtimex",
"ME sys_mprotect",
"SI sys_sigprocmask",
"ZZ",
"LO sys_init_module",
"LO sys_delete_module",
"ZZ",
"FI sys_quotactl",
"PR ID sys_getpgid",
"FD sys_fchdir",
"LO sys_bdflush",
"FI sys_sysfs",
"PR SI sys_personality",
"ZZ",
"ID sys_setfsuid16",
"ID sys_setfsgid16",
"FD sys_llseek",
"FD sys_getdents",
"LO sys_select",
"FD sys_flock",
"ME sys_msync",
"FD sys_readv",
"FD sys_writev",
"ID sys_getsid",
"FD sys_fdatasync",
"LO sys_sysctl",
"ME sys_mlock",
"ME sys_munlock",
"ME sys_mlockall",
"ME sys_munlockall",
"PR sys_sched_setparam",
"PR sys_sched_getparam",
"PR sys_sched_setscheduler",
"PR sys_sched_getscheduler",
"PR sys_sched_yield",
"PR sys_sched_get_priority_max",
"PR sys_sched_get_priority_min",
"PR sys_sched_rr_get_interval",
"PR TI sys_nanosleep",
"ME sys_mremap",
"ID sys_setresuid16",
"ID sys_getresuid16",
"LO sys_vm86",
"ZZ",
"FD sys_poll",
"ZZ",
"ID sys_setresgid16",
"ID sys_getresgid16",
"PR sys_prctl",
"SI sys_rt_sigreturn",
"SI rt_sigaction",
"SI sys_rt_sigprocmask",
"SI sys_rt_sigpending",
"SI sys_rt_sigtimedwait",
"SO sys_rt_sigqueueinfo",
"SI sys_rt_sigsuspend",
"FD sys_pread64",
"FD sys_pwrite64",
"FI sys_chown16",
"FI sys_getcwd",
"PR sys_capget",
"PR sys_capset",
"SI sys_sigaltstack",
"FD sys_sendfile",
"ZZ",
"ZZ",
"PR sys_vfork",
"PR sys_getrlimit",
"ME sys_mmap_pgoff",
"FI sys_truncate64",
"FD sys_ftruncate64",
"FI sys_stat64",
"FI sys_lstat64",
"FD sys_fstat64",
"FI sys_lchown",
"ID sys_getuid",
"ID sys_getgid",
"ID sys_geteuid",
"ID sys_getegid",
"ID sys_setreuid",
"ID sys_setregid",
"ID sys_getgroups",
"ID sys_setgroups",
"FD sys_fchown",
"ID sys_setresuid",
"ID sys_getresuid",
"ID sys_setresgid",
"ID sys_getresgid",
"FI sys_chown",
"ID sys_setuid",
"ID sys_setgid",
"ID sys_setfsuid",
"ID sys_setfsgid",
"FI sys_pivot_root",
"ME sys_mincore",
"ME sys_madvise",
"FD sys_getdents64",
"FD sys_fcntl64",
"ZZ",
"ZZ",
"PR sys_gettid",
"FD sys_readahead",
"FI sys_setxattr",
"FI sys_lsetxattr",
"FI sys_fsetxattr",
"FI sys_getxattr",
"FI sys_lgetxattr",
"FI sys_fgetxattr",
"FI sys_listxattr",
"FI sys_llistxattr",
"FI sys_flistxattr",
"FI sys_removexattr",
"FI sys_lremovexattr",
"FI sys_fremovexattr",
"PR sys_tkill",
"FD sys_sendfile64",
"LK sys_futex",
"PR sys_sched_setaffinity",
"PR sys_sched_getaffinity",
"ME set_thread_area",
"ME get_thread_area",
"LO sys_io_setup",
"LO sys_io_destroy",
"LO sys_io_getevents",
"LO sys_io_submit",
"LO sys_io_cancel",
"FD sys_fadvise64",
"ZZ",
"PR sys_exit_group",
"FI sys_lookup_dcookie",
"LO FD sys_epoll_create",
"LO FD sys_epoll_ctl",
"LO FD sys_epoll_wait",
"ME sys_remap_file_pages",
"PR sys_set_tid_address",
"SI TR sys_timer_create",
"SI TR sys_timer_settime",
"SI TR sys_timer_gettime",
"SI TR sys_timer_getoverrun",
"SI TR sys_timer_delete",
"SI TR sys_clock_settime",
"SI TR sys_clock_gettime",
"SI TR sys_clock_getres",
"SI TR sys_clock_nanosleep",
"FI sys_statfs64",
"FD sys_fstatfs64",
"PR sys_tgkill",
"FI sys_utimes",
"FD sys_fadvise64_64",
"ZZ",
"ME sys_mbind",
"ME sys_get_mempolicy",
"ME sys_set_mempolicy",
"IP sys_mq_open",
"IP sys_mq_unlink",
"IP sys_mq_timedsend",
"IP sys_mq_timedreceive",
"IP sys_mq_notify",
"IP sys_mq_getsetattr",
"LO sys_kexec_load",
"PR sys_waitid",
"ZZ",
"LO sys_add_key",
"LO sys_request_key",
"LO sys_keyctl",
"LO sys_ioprio_set",
"LO sys_ioprio_get",
"FI sys_inotify_init",
"FI sys_inotify_add_watch",
"FI sys_inotify_rm_watch",
"ME sys_migrate_pages",
"FD FI sys_openat",
"FD FI sys_mkdirat",
"FD FI sys_mknodat",
"FD FI sys_fchownat",
"FD FI sys_futimesat",
"FD FI sys_fstatat64",
"FD FI sys_unlinkat",
"FD FI sys_renameat",
"FD FI sys_linkat",
"FD FI sys_symlinkat",
"FD FI sys_readlinkat",
"FD FI sys_fchmodat",
"FD FI sys_faccessat",
"FD sys_pselect6",
"FD sys_ppoll",
"PR sys_unshare",
"LK sys_set_robust_list",
"LK sys_get_robust_list",
"FD sys_splice",
"FD sys_sync_file_range",
"FD sys_tee",
"FD ME sys_vmsplice",
"ME sys_move_pages",
"LO sys_getcpu",
"LO FD sys_epoll_pwait",
"FD FI sys_utimensat",
"FD SI sys_signalfd",
"TR FD sys_timerfd_create",
"TR FD sys_eventfd",
"FD sys_fallocate",
"FD TR sys_timerfd_settime",
"FD TR sys_timerfd_gettime",
"SI sys_signalfd4",
"FD SI sys_eventfd2",
"LO FD sys_epoll_create1",
"FD sys_dup3",
"FD sys_pipe2",
"FI sys_inotify_init1",
"FD sys_preadv",
"FD sys_pwritev",
"SI sys_rt_tgsigqueueinfo",
"PR sys_perf_event_open",
"NE IP sys_recvmmsg",
"FI sys_fanotify_init",
"FI sys_fanotify_mark",
"PR sys_prlimit64",
"FD FI sys_name_to_handle_at",
"FD sys_open_by_handle_at",
"TI sys_clock_adjtime",
"FD FI sys_syncfs",
"NE IP sys_sendmmsg",
"PR sys_setns",
"ME PR sys_process_vm_readv",
"ME PR sys_process_vm_writev",
};
#endif
